# Configuración de la Aplicación
app:
  replicaCount: 2
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  ingress:
    enabled: true
    hosts:
      - host: app.local
        paths: ["/"]

# Configuración de la Base de Datos
db:
  user: root
  password: root_password
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard


