apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-namespace
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA== # root_password
  mysql-user: dXNlcm5hbWU= # username
  mysql-password: cGFzc3dvcmQ= # password

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app-namespace
type: Opaque
data:
  db-username: dXNlcm5hbWU= # username
  db-password: cGFzc3dvcmQ= # password

