apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion
  namespace: app-namespace
spec:
  type: NodePort  # Exponer el servicio en un puerto específico
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Puedes elegir un puerto entre 30000 y 32767



