apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.configMapName }}
  namespace: {{ .Values.app.namespace }}
data:
  database_name: {{ .Values.db.database_name }}
  database_host: {{ .Values.db.database_host }}
