apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-db-config
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
data:
  database_name: {{ .Values.mariadb.auth.database | quote }}
  database_host: {{ include "my-helm-chart.fullname" . }}-mariadb-headless
