apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-hpa
  namespace: {{ .Values.app.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}  # Hace referencia al nombre del deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}  # Umbral de uso de CPU para escalar
  {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
  targetMemoryUtilizationPercentage: {{ .Values.hpa.targetMemoryUtilizationPercentage }}  # Umbral de uso de memoria (opcional)
  {{- end }}

