apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-secret
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # Campos del Secret de MariaDB
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.user | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | b64enc | quote }}

  # Campo del Secret de la aplicación
  DATABASE_URL: {{ printf "mysql+pymysql://%s:%s@%s-mariadb-headless:3306/%s" .Values.mariadb.auth.user .Values.mariadb.auth.password (include "my-helm-chart.fullname" .) .Values.mariadb.auth.database | b64enc }}

