apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  db-username: {{ .Values.db.username }}
  db-password: {{ .Values.db.password }}
