apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-mariadb
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
  selector:
    {{- include "my-helm-chart.mariadbSelectorLabels" . | nindent 4 }}


